name: Convert EPG Data to Enigma2 Format

on:
  push:
    branches: [main]

jobs:
  convert-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xmltodict

    - name: Convert EPG XML to Enigma2 XML
      run: |
        python convert_epg.py

    - name: Commit and push converted EPG
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add EPG_Enigma2.xml
        git commit -m 'Add converted Enigma2 EPG data'
        git push
