name: EPG Scraping

# Controls when the action will run. In this case, it is scheduled to run daily at 6 AM UTC.
on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at 6 AM UTC
  push:
    branches:
      - main  # Also runs when changes are pushed to the main branch

jobs:
  scrape_epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pyyaml

    - name: Run EPG Scraper
      run: |
        python epg_scraper.py

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: epg-result
        path: result.txt  # Assuming your script outputs to result.txt
